### ISSUE TITLE
More interesting Games tile

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#900]
![image 8](https://user-images.githubusercontent.com/611168/48095020-e23e9700-e1d0-11e8-8c88-786be19512ff.png)

```css
.category.games {
    background-image:
        linear-gradient(
            to bottom,
            mix(@SLATE_500, @BLUEBERRY_500, 0.5),
            @SLATE_900
        );
    border-color: alpha(@SLATE_900, 0.8);
    box-shadow:
        inset 0 0 0 1px alpha(white, 0.02),
        inset 0 1px 0 0 alpha(white, 0.23),
        inset 0 -1px 0 0 alpha(white, 0.07),
        0 3px 2px -1px alpha(black, 0.15),
        0 3px 5px alpha(@BLACK_900, 0.1);
    color: shade(@BLUEBERRY_100, 1.1);
    font-size: 26px;
    font-weight: 700;
    text-shadow: 0 1px 2px alpha(@BLACK_900, 0.8);
    -gtk-icon-shadow: 0 1px 2px alpha(@BLACK_900, 0.8);
}
```
